version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: finance-transaction-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: finance
      POSTGRES_DB: finance_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

